# Generated by Django 5.1 on 2024-09-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventorganizer.events')),
            ],
        ),
    ]
