# Generated by Django 5.1 on 2024-09-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Events',
            new_name='event',
        ),
    ]
